### ISSUE TITLE
Credentials for MariaDB

### ISSUE THREAD

**Issue by JonasOelke** [bloodhunterd/froxlor-docker#2]
Thank you for your great work! I tried to get froxlor running in docker. It worked fine until I came to the Webinstaller page where I have to insert the root credentials for the database. I though it might be "root" or I could leave it blank (this does not work because froxlor forces me to put a password in). 

So my next though would be to login to the console of the docker image and set a MariaDB password. But is your script meant to work like this or is it just me not understanding where to get (or set) the password from? 

Best regards, 
Jonas

**Comment by bloodhunterd** [comment]
The image contains only the client so you need a separate server. You can use the Docker image of MariaDB and set there the credentials for the root and froxlor user.

I also have to say that Froxlor isn't meant to be work as Docker image by design so it can be difficult to get everything set up and running sometimes.
